In [7]:
import pandas as pd

fileName=r'C:\Users\mike\Documents\ArcGIS\Projects\Assignements\week5\peerGradeW5\week5_data\covid\daily.csv'
index_col=['date', 'state']

In [8]:
df = pd.read_csv(fileName, index_col=index_col)
df.sort_index()
df

                positive  negative  pending  hospitalizedCurrently  \
date     state
20200501 AK        364.0   19961.0      NaN                   25.0
         AL       7158.0   84775.0      NaN                    NaN
         AR       3321.0   46355.0      NaN                   95.0
         AS          0.0      57.0      NaN                    NaN
         AZ       7962.0   66917.0      NaN                  709.0
...                  ...       ...      ...                    ...
20200126 WA          1.0       NaN      NaN                    NaN
20200125 WA          1.0       NaN      NaN                    NaN
20200124 WA          1.0       NaN      NaN                    NaN
20200123 WA          1.0       NaN      NaN                    NaN
20200122 WA          1.0       NaN      NaN                    NaN

                hospitalizedCumulative  inIcuCurrently  inIcuCumulative  \
date     state
20200501 AK                        NaN             NaN              NaN
         AL                     1008.0             NaN            335.0
         AR                      414.0             NaN              NaN
         AS                        NaN             NaN              NaN
         AZ                     1203.0           311.0              NaN
...                                ...             ...              ...
20200126 WA                        NaN             NaN              NaN
20200125 WA                        NaN             NaN              NaN
20200124 WA                        NaN             NaN              NaN
20200123 WA                        NaN             NaN              NaN
20200122 WA                        NaN             NaN              NaN

                onVentilatorCurrently  onVentilatorCumulative  recovered  ...  \
date     state                                                            ...
20200501 AK                       NaN                     NaN      254.0  ...
         AL                       NaN                   195.0        NaN  ...
         AR                      23.0                    85.0     1973.0  ...
         AS                       NaN                     NaN        NaN  ...
         AZ                     187.0                     NaN     1528.0  ...
...                               ...                     ...        ...  ...
20200126 WA                       NaN                     NaN        NaN  ...
20200125 WA                       NaN                     NaN        NaN  ...
20200124 WA                       NaN                     NaN        NaN  ...
20200123 WA                       NaN                     NaN        NaN  ...
20200122 WA                       NaN                     NaN        NaN  ...

               hospitalized    total  totalTestResults   posNeg  fips  \
date     state
20200501 AK             NaN  20325.0           20325.0  20325.0     2
         AL          1008.0  91933.0           91933.0  91933.0     1
         AR           414.0  49676.0           49676.0  49676.0     5
         AS             NaN     57.0              57.0     57.0    60
         AZ          1203.0  74879.0           74879.0  74879.0     4
...                     ...      ...               ...      ...   ...
20200126 WA             NaN      1.0               1.0      1.0    53
20200125 WA             NaN      1.0               1.0      1.0    53
20200124 WA             NaN      1.0               1.0      1.0    53
20200123 WA             NaN      1.0               1.0      1.0    53
20200122 WA             NaN      1.0               1.0      1.0    53

                deathIncrease  hospitalizedIncrease  negativeIncrease  \
date     state
20200501 AK               0.0                   0.0            1197.0
         AL              10.0                  30.0            4598.0
         AR               3.0                  12.0            1231.0
         AS               0.0                   0.0              54.0
         AZ              10.0                  34.0            2779.0
...                       ...                   ...               ...
20200126 WA               0.0                   0.0               0.0
20200125 WA               0.0                   0.0               0.0
20200124 WA               0.0                   0.0               0.0
20200123 WA               0.0                   0.0               0.0
20200122 WA               NaN                   NaN               NaN

                positiveIncrease  totalTestResultsIncrease
date     state
20200501 AK                  9.0                    1206.0
         AL                139.0                    4737.0
         AR                 66.0                    1297.0
         AS                  0.0                      54.0
         AZ                314.0                    3093.0
...                          ...                       ...
20200126 WA                  0.0                       0.0
20200125 WA                  0.0                       0.0
20200124 WA                  0.0                       0.0
20200123 WA                  0.0                       0.0
20200122 WA                  NaN                       NaN

[3209 rows x 23 columns]

In [12]:
df.loc[20200423].to_csv(r'C:\Users\mike\Documents\ArcGIS\Projects\Assignements\week5\peerGradeW5\week5_data\covid\daily_20200423.csv')

In [13]:
df.loc[20200410].to_csv(r'C:\Users\mike\Documents\ArcGIS\Projects\Assignements\week5\peerGradeW5\week5_data\covid\daily_20200410.csv')